/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'initializeAdmin' : IDL.Func([], [], []),
  'initializeDefaultContactInfo' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'initializeAdmin' : IDL.Func([], [], []),
    'initializeDefaultContactInfo' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };